"""Configuration — 12-factor, loaded from environment (.env supported).

Nothing secret is committed. Copy the documented variables into a local
`.env` file (gitignored) or export them in the systemd unit.
"""
from __future__ import annotations

import os
from dataclasses import dataclass, field
from pathlib import Path

from dotenv import load_dotenv

from .log import log

# Load .env sitting next to the project root, if present.
_PROJECT_ROOT = Path(__file__).resolve().parents[2]
load_dotenv(_PROJECT_ROOT / ".env")


def _bool(name: str, default: bool) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


def _int(name: str, default: int) -> int:
    raw = os.getenv(name)
    if raw is None or not raw.strip():
        return default
    try:
        return int(raw.strip())
    except ValueError:
        # A typo'd env (e.g. POLL_INTERVAL=30s) silently falling back to the default
        # is a trap — say so. (`os.getenv(...)` is always a str, so the old
        # AttributeError arm was unreachable; dropped.)
        log.warning("env %s=%r is not an integer; using default %d", name, raw, default)
        return default


# ---- Sheet layout (fixed, daemon bootstraps it) ---------------------------
# There is NO Product Vision row: row 1 is the config row + heartbeat, row 2 is the
# task header, tasks start at row 3.
CONFIG_ROW = 1          # A1=Репозиторий label, B1=value, C1=Ветка label, D1=value
HEADER_ROW = 2          # column headers
FIRST_TASK_ROW = 3      # first task row

# Russian, human-friendly config-row labels. A1 labels the repo binding (which lives
# in B1) and C1 labels the branch (D1). The labels are cosmetic sentinels: the binding
# is read by POSITION (B1/D1), never by the label, so relabelling is safe. The old
# English labels (`REPO_PATH`/`BRANCH`) are migrated in place by `_migrate_russianize`.
CONFIG_LABEL_REPO = "Репозиторий"
CONFIG_LABEL_BRANCH = "Ветка"

# Daemon heartbeat lives in E1 (row 1, col 5): the config row's first empty cell.
# NOTE: the config row (row 1) is hidden by `prettify` ("чат без лишнего"), so this
# is a DURABLE forensic liveness record (visible only when the row is unhidden), not
# an at-a-glance UI signal. The live operator signal is `journalctl --user -u
# harness-google-sheet`. The write is throttled (see Orchestrator._hb) so it costs
# negligible Sheets quota.
HEARTBEAT_ROW = 1       # E1
HEARTBEAT_COL = 5       # E
COL_REPO_BINDING = 2    # B  repo binding lives in B1 (config row)

# First line of docs/strategy/vision.md, written verbatim by
# `scripts/create_beelink_repo.sh` when a NEW repo is provisioned — a repo artifact
# seeded ONCE at creation, NOT a sheet feature (the sheet has no Product Vision).
# Single source of truth so the byte-exact marker can never drift; note the em-dash
# (U+2014), not a hyphen.
VISION_AUTOGEN_HEADER = (
    "<!-- AUTOGENERATED FROM GOOGLE SHEET — edit in the sheet, not here -->"
)

# The DETERMINISTIC repo-provisioning engine, invoked by BOTH the daemon
# `create_repo` handler and the `create-beelink-repo` skill (one engine, two
# entry points). No LLM in the critical path — creating a GitHub repo is
# irreversible, so it is plain ordered bash. Tests override CREATE_REPO_SCRIPT
# with a stub so nothing hits the network.
CREATE_REPO_SCRIPT = str(_PROJECT_ROOT / "scripts" / "create_beelink_repo.sh")

# 1-indexed columns. The visible grid is 6 wide (A–F); there is no human "Detail"
# column (removed) and no human "Priority" column (removed — tasks run in row
# order). The `run_skill` path carries its own extra context (the dialog `detail`
# in `_control` args), so per-task extra context is unaffected.
#
# Tries (F) is daemon-owned DURABLE state (dead-lettering / rate-limit backoff),
# not human data — the column is HIDDEN by `prettify` so the human sees A–E, but
# the counter keeps living in F because the durable-state invariant forbids moving
# it into local `state/`.
COL_TASK = 1            # A  human task description (input)
COL_SPEC = 2            # B  openspec change id (daemon); its cell NOTE holds the full
                        #    spec for review (proposal + deltas) when a gated spec is ready
COL_SPEC_NOTE_MAX = 20000  # cap on the spec-review note attached to the Спека cell
COL_STATUS = 3         # C  status (daemon-managed)
COL_UPDATED = 4        # D  last-updated timestamp (daemon)
COL_LOG = 5            # E  last agent summary / error / link (daemon)
COL_TRIES = 6          # F  dispatch attempt counter (daemon; hidden from view)

# Russian, human-friendly column headers (same A–F layout; Попытки/Tries hidden).
# The English header (`Task,…`) is migrated in place by `_migrate_russianize`.
HEADERS = ["Задача", "Спека", "Статус", "Обновлено", "Итог", "Попытки"]

# ---- Per-repo chat (a dedicated PAIRED chat tab) --------------------------
# A read-only Q&A channel for discussing one repo without changing code. It lives on
# its OWN tab — `_chat <repo>` — paired to the repo task tab by the SAME B1 binding
# (NOT by parsing the title). The title starts with META_PREFIX so the repo-dispatch
# loop skips it: no task schema, no task dispatch. The top rows are frozen (see
# ensure_chat_schema) so the compose box and the pinned latest answer stay on screen
# while the transcript scrolls (messenger-style "latest at hand").
#
# Layout (compact, columns A/B):
#   A1 = REPO_PATH label, B1 = repo binding (shared with the repo tab — the pair key).
#   A2 = compose box: the human types the next question here (human-owned input).
#   B2 = pinned latest answer (daemon).
#   A3/B3 = chat headers.
#   A4.. / B4.. = transcript, newest at the BOTTOM. The daemon owns the WHOLE
#                 transcript: it echoes the human's question into A{n} and writes the
#                 reply into B{n}, so the human's only input surface is A2.
#
# Chat tabs are titled with this prefix; pairing is by B1 binding, never by name.
CHAT_TAB_PREFIX = "_chat "
CHAT_INPUT_ROW = 2       # A2 compose box
CHAT_INPUT_COL = 1       # A
CHAT_PINNED_ROW = 2      # B2 pinned latest answer
CHAT_PINNED_COL = 2      # B
CHAT_HEADER_ROW = 3      # A3/B3
CHAT_FIRST_ROW = 4       # transcript grows down from here
COL_CHAT_Q = 1           # A  transcript question (daemon echoes the human's input)
COL_CHAT_A = 2           # B  transcript answer (daemon)

CHAT_HEADERS = ["Ты (вопрос)", "Агент (ответ)"]      # A3, B3
CHAT_THINKING = "⏳ думаю…"          # placeholder shown while the agent runs
CHAT_MAX_ANSWER = 8000              # cap an answer/pin so a runaway reply can't bloat a cell
# Visible self-advertising prompt seeded into an EMPTY compose box A2 so the human can
# SEE where/how to talk to the agent (an empty cell announces nothing). The daemon
# treats this exact string as "no question" (never dispatches it) and re-seeds it after
# consuming a real question, so the cue is always present. Single source of truth so
# the daemon's "is-empty" check and the seed can never drift.
CHAT_INPUT_PLACEHOLDER = (
    "✍️ Напиши вопрос агенту про этот репозиторий и нажми Enter. Read-only — код не меняется."
)
CHAT_INPUT_NOTE = (
    "Пиши вопрос прямо в эту ячейку и жми Enter. Можно без кода — обсудить, разобраться. "
    "Демон ответит ниже, последний ответ продублирует справа → B2. Read-only: код не меняется."
)
CHAT_PINNED_NOTE = "Последний ответ агента (read-only обсуждение). Полная история — ниже."

# Tabs whose title starts with this prefix are meta/reference sheets — the daemon
# never treats them as a repo tab (no bootstrap, no dispatch).
META_PREFIX = "_"
REPOS_TAB = "_repos"    # reference list of selectable repos (B1 dropdown source)

# ---- Skills catalog (`_skills` meta-tab) ----------------------------------
# A human-curated catalog of runnable playbooks. Each row is one skill the human can
# pick from the `▶️ Запустить скилл` menu and run against the active repo tab. Layout:
#   A=Skill (the picker value), B=Description (human-facing), C=Prompt (agent-facing —
#   the task the daemon feeds the agent). The sheet is the source of truth: edit a
#   prompt here and the next run uses it. Unlike `_repos` (rebuilt from discovery each
#   time), `_skills` is seeded ONCE (only when absent/empty) so prunes/edits survive.
SKILLS_TAB = "_skills"
SKILLS_HEADER_ROW = 1
SKILLS_FIRST_ROW = 2
COL_SKILL_NAME = 1     # A  skill name (picker value)
COL_SKILL_DESC = 2     # B  human-facing description
COL_SKILL_PROMPT = 3   # C  agent-facing prompt (what the daemon runs)
COL_SKILL_RUN = 4      # D  visible "how to run" trigger string `/<name>` (human copy)
# Russian, human-friendly headers. The `Запуск` column shows the exact trigger string
# so the human can SEE how to run each skill (type it into a repo task cell). An old
# English catalog (`Skill, Description, Prompt`) is migrated in place by
# `_migrate_skills_layout` (header Russianised + `Запуск` filled) without re-seeding.
SKILLS_HEADERS = ["Скилл", "Описание", "Промпт", "Запуск"]

# The slash prefix that turns a repo task cell into a "run this catalog skill" command:
# `/<скилл> [доп. контекст]`. Single source of truth so the parser (orchestrator) and
# the visible `Запуск` trigger string can never drift.
SKILL_TRIGGER_PREFIX = "/"


def skill_trigger(name: str) -> str:
    """The visible/typed trigger string for a skill: `/<name>`. Used for the catalog's
    `Запуск` column and recognised in a repo task cell by the orchestrator."""
    return f"{SKILL_TRIGGER_PREFIX}{name}"


@dataclass(frozen=True)
class SkillDef:
    """One catalog skill: a name (picker value), a human-facing description, and the
    agent-facing prompt the daemon runs as the task when the skill is dispatched."""
    name: str
    description: str
    prompt: str


# The seeded catalog. Deliberately BROAD (the operator prunes what they don't want).
# Descriptions are Russian (human-facing, matching the sheet UI); prompts are English
# (agent-facing, matching agent.py). Each prompt is a self-contained task statement —
# `agent.run` wraps it in the full OpenSpec spec→implement→ship pipeline, so a skill run
# is always expressed as an OpenSpec change. `autopilot` reads the human's extra context.
DEFAULT_SKILLS: tuple[SkillDef, ...] = (
    SkillDef(
        "autopilot",
        "Автопилот: под ключ реализовать задачу из доп. контекста (спека→код→тесты→деплой).",
        "Deliver the change described in the extra context end-to-end. If no extra "
        "context is given, pick the single highest-value improvement for this repo and "
        "deliver that.",
    ),
    SkillDef(
        "idea",
        "Идеи фич: придумать список новых полезных фич для проекта (в бэклог-файл + краткий список в лог).",
        "Brainstorm a prioritised list of genuinely new, high-value features or "
        "improvements for THIS project. First study the codebase, README and docs so "
        "every idea is grounded in what the project actually does and who uses it. For "
        "each idea give a short title, the concrete user value it delivers, and a rough "
        "effort estimate (S/M/L). Record the full list as a durable backlog document "
        "under docs/ideas/ in the repo — create it or extend the existing one, and do "
        "not duplicate ideas already listed there. Do NOT implement any of the features: "
        "this is ideation only. Make your final summary a concise numbered list of just "
        "the idea titles so the most promising features are readable at a glance.",
    ),
    SkillDef(
        "add-tests",
        "Поднять покрытие тестами: найти слабо покрытые места и осмысленно их покрыть.",
        "Raise this repository's test coverage: find the most important under-tested "
        "modules or code paths and add meaningful, non-trivial tests for them. Do not "
        "weaken existing tests.",
    ),
    SkillDef(
        "harden",
        "Укрепить надёжность: обработка ошибок, краевые случаи, защита от падений.",
        "Audit this repository for robustness gaps — unhandled errors, missing edge-case "
        "handling, crash-prone paths — and fix the most impactful ones without changing "
        "intended behaviour.",
    ),
    SkillDef(
        "simplify",
        "Упростить код: убрать дублирование и сложность без изменения поведения.",
        "Find the most complex or duplicated code in this repository and simplify it — "
        "reduce duplication, clarify control flow, improve naming — strictly without "
        "changing observable behaviour. Tests must still pass.",
    ),
    SkillDef(
        "refresh-docs",
        "Обновить документацию: README / CLAUDE.md / докстринги под текущий код.",
        "Bring this repository's documentation back in sync with the code: update the "
        "README, CLAUDE.md and key docstrings so they accurately describe the current "
        "behaviour. Do not change code behaviour.",
    ),
    SkillDef(
        "security-pass",
        "Security-проход: найти и починить уязвимости и небезопасные места.",
        "Do a focused security pass on this repository: look for injection, secret "
        "handling, unsafe input, permission and dependency issues, and fix the most "
        "serious ones you find.",
    ),
    SkillDef(
        "fix-flaky-tests",
        "Починить флакающие / хрупкие тесты, не ослабляя проверки.",
        "Find flaky or brittle tests in this repository (timing-dependent, order-"
        "dependent, network-dependent) and make them deterministic without weakening "
        "what they assert.",
    ),
    SkillDef(
        "perf-pass",
        "Оптимизировать заметное узкое место производительности.",
        "Find one clear performance bottleneck in this repository and optimise it, "
        "measuring or reasoning about the win and keeping behaviour identical.",
    ),
    SkillDef(
        "dependency-bump",
        "Безопасно обновить зависимости (тесты должны пройти).",
        "Update this repository's dependencies to safe, current versions, adjusting code "
        "for any breaking changes, and make sure the test suite passes before shipping.",
    ),
    SkillDef(
        "cleanup-deadcode",
        "Удалить мёртвый код, неиспользуемые ветки и файлы.",
        "Find and remove dead code in this repository — unused functions, unreachable "
        "branches, orphaned files — verifying with tests that nothing live is removed.",
    ),
    SkillDef(
        "error-messages",
        "Сделать сообщения об ошибках понятными и actionable.",
        "Improve the error messages and diagnostics in this repository so a human reading "
        "them knows what went wrong and what to do next.",
    ),
    SkillDef(
        "code-review",
        "Ревью свежих изменений: найти баги корректности и сразу починить.",
        "Review the most recent changes in this repository (the latest commits / the "
        "current diff against the main branch) for correctness bugs, then fix the real "
        "ones you find. Prefer high-confidence issues over speculative ones.",
    ),
    SkillDef(
        "ux-loop-fix",
        "Пройтись по живому сайту как пользователь и починить заметные UX-баги.",
        "Walk this project's live user-facing surface the way a real user would, find the "
        "most damaging visible UX / UI / copy / flow problems, and fix the worst one — "
        "adding a regression test first so it cannot come back. Keep changes minimal and "
        "behaviour-preserving elsewhere.",
    ),
    SkillDef(
        "pagespeed",
        "Ускорить сайт: улучшить Lighthouse / Core Web Vitals.",
        "Improve this project's web performance: identify one clear page-speed bottleneck "
        "(bundle size, render-blocking assets, images, caching, slow endpoints) and fix "
        "it, reasoning about the win and keeping behaviour identical.",
    ),
    SkillDef(
        "accessibility",
        "A11y-проход: семантика, контраст, клавиатура, ARIA по WCAG.",
        "Do an accessibility pass on this project's user interface: fix the most impactful "
        "WCAG issues — semantic structure, colour contrast, keyboard navigation, focus "
        "order, labels and ARIA — without changing intended behaviour.",
    ),
    SkillDef(
        "observability",
        "Добавить наблюдаемость: структурные логи, метрики, health-проверки.",
        "Improve this repository's observability: add or improve structured logging, "
        "useful metrics and health checks on the most important code paths so failures "
        "are diagnosable in production. Do not change intended behaviour.",
    ),
    SkillDef(
        "ci-setup",
        "Завести / починить CI: линт + тесты на каждый push.",
        "Set up or repair continuous integration for this repository so that lint and the "
        "test suite run automatically on every push, using the CI system this project "
        "already targets (or the conventional one for its stack if none exists).",
    ),
    SkillDef(
        "type-coverage",
        "Усилить типизацию: добавить аннотации и включить проверку типов.",
        "Strengthen this repository's static typing: add or tighten type annotations on "
        "the most important modules and wire up (or fix) the type checker so it passes, "
        "without changing runtime behaviour.",
    ),
    SkillDef(
        "lint-format",
        "Привести код к единому стилю: настроить линтер/форматтер и починить нарушения.",
        "Establish consistent formatting and linting for this repository: configure the "
        "standard formatter and linter for its stack, then fix the violations. Changes "
        "must be style-only — no behavioural change, tests still pass.",
    ),
    SkillDef(
        "resilience-retries",
        "Сделать внешние вызовы устойчивыми: таймауты, ретраи, backoff.",
        "Make this repository's calls to external services resilient: add sensible "
        "timeouts, retries with backoff and failure handling where they are missing, so a "
        "flaky dependency degrades gracefully instead of crashing.",
    ),
    SkillDef(
        "input-validation",
        "Валидировать и санитизировать внешние входные данные.",
        "Harden this repository's handling of external input: validate and sanitise data "
        "coming from users, requests, files and APIs at the boundaries, rejecting bad "
        "input clearly instead of letting it propagate. Keep valid behaviour unchanged.",
    ),
    SkillDef(
        "api-docs",
        "Описать API: эндпойнты, параметры, примеры запросов/ответов.",
        "Document this repository's public API: its endpoints or exported interface, their "
        "parameters and return shapes, with accurate request/response examples. Generate "
        "docs from the code where possible; do not change behaviour.",
    ),
    SkillDef(
        "onboarding-docs",
        "Упростить онбординг разработчика: быстрый старт, setup, contributing.",
        "Improve developer onboarding for this repository: a clear quickstart, an accurate "
        "local setup that actually works from a clean checkout, and contributing notes, so "
        "a new developer is productive fast. Documentation only — no behaviour change.",
    ),
)

# ---- Control intent queue (`_control` meta-tab) ---------------------------
# Apps Script appends intent rows (id/ts/action/args); the daemon dispatches
# them, owning ONLY status (E) and result (F). Layout is its own grid — header
# on row 1, data from row 2 — NOT the A..H task layout above. `_control` starts
# with META_PREFIX so the repo-dispatch loops skip it automatically.
CONTROL_TAB = "_control"   # intent queue: Apps Script appends, daemon dispatches
CONTROL_HEADER_ROW = 1
CONTROL_FIRST_ROW = 2

# 1-indexed control columns
COL_CTL_ID = 1       # A  unique idempotency key (Apps Script)
COL_CTL_TS = 2       # B  ISO click time (Apps Script)
COL_CTL_ACTION = 3   # C  add_repo|create_repo|run_skill (Apps Script)
COL_CTL_ARGS = 4     # D  JSON args (Apps Script)
COL_CTL_STATUS = 5   # E  pending->working->done|error (daemon)
COL_CTL_RESULT = 6   # F  link/result/error text (daemon)

CONTROL_HEADERS = ["id", "ts", "action", "args", "status", "result"]

# ---- Friend sheets registry (`_friends` meta-tab) -------------------------
# The durable registry of every shared "friend" file the owner has minted: which
# spreadsheet, which repos it is allowed to operate on (per-sheet allowlist), who it
# is shared with, its autonomy level and its URL. Lives on the MASTER sheet (the
# sheet is the single source of truth — no local registry that could drift). Layout
# is its own grid (header row 1, data from row 2), and `_friends` starts with
# META_PREFIX so the repo-dispatch loops never treat it as a repo tab.
FRIENDS_TAB = "_friends"
FRIENDS_HEADER_ROW = 1
FRIENDS_FIRST_ROW = 2

# 1-indexed friend columns
COL_FRIEND_SHEET_ID = 1   # A  the friend spreadsheet id
COL_FRIEND_REPOS = 2      # B  newline/comma-separated repo allowlist
COL_FRIEND_RECIPIENT = 3  # C  e-mail the file is shared with
COL_FRIEND_AUTONOMY = 4   # D  per-sheet autonomy (blank → FRIEND_DEFAULT_AUTONOMY)
COL_FRIEND_LINK = 5       # E  spreadsheet URL (human convenience)

FRIENDS_HEADERS = ["sheet_id", "repos", "recipient", "autonomy", "link"]

# The control action that mints + shares a new friend file from the master sheet.
ACTION_SHARE_REPOS = "share_repos"

# Control actions. Most are fast synchronous admin ops (add_repo/create_repo) run
# inline by the dispatcher. `run_skill` is ASYNC: it dispatches a long delivery agent
# through the background pool instead of blocking the poll loop.
ACTION_RUN_SKILL = "run_skill"
ASYNC_CONTROL_ACTIONS = {ACTION_RUN_SKILL}

# Control status vocabulary (distinct from the task statuses above)
CTL_PENDING = "pending"
CTL_WORKING = "working"
CTL_DONE = "done"
CTL_ERROR = "error"

# Status vocabulary
ST_QUEUED = "queued"       # picked up next cycle
ST_RETRY = "retry"         # human asks to re-run a failed task (resets Tries)
ST_WORKING = "working"     # agent currently running
ST_DONE = "done"           # shipped
ST_FAILED = "failed"       # agent failed; needs human
ST_BLOCKED = "blocked"     # cannot proceed (e.g. no openspec, no repo)
ST_SPEC_READY = "spec_ready"  # gated: spec written, waiting human approval
ST_APPROVED = "approved"      # gated: human approved spec → implement (resets Tries)

# Every status the daemon may write or a human may set — used for the Status
# dropdown. Ordered human-first for a sensible picker.
ALL_STATUSES = [
    ST_QUEUED, ST_RETRY, ST_APPROVED, ST_SPEC_READY,
    ST_WORKING, ST_DONE, ST_FAILED, ST_BLOCKED,
]

# At-a-glance colour cue for the Status column: status -> (r, g, b) in 0..1 fractions
# (the Sheets API colour shape). Soft fills so the status text stays readable. Covers
# EVERY status in ALL_STATUSES (a test enforces this); the formatting pass turns these
# into conditional-format rules on the Status column.
STATUS_COLORS: dict[str, tuple[float, float, float]] = {
    ST_QUEUED:     (0.85, 0.92, 1.00),   # light blue — waiting to be picked up
    ST_RETRY:      (1.00, 0.90, 0.70),   # light orange — human asked to re-run
    ST_APPROVED:   (0.80, 0.95, 0.80),   # light green — approved, will ship
    ST_SPEC_READY: (0.90, 0.85, 1.00),   # light purple — spec parked for approval
    ST_WORKING:    (1.00, 0.97, 0.75),   # light yellow — agent running now
    ST_DONE:       (0.72, 0.92, 0.72),   # green — shipped
    ST_FAILED:     (0.97, 0.78, 0.78),   # red — failed, needs a human
    ST_BLOCKED:    (0.85, 0.85, 0.85),   # grey — cannot proceed
}

# Blank or these → actionable. `approved` triggers the implement phase in gated
# mode. `spec_ready` is intentionally NOT here — it parks until a human approves.
ACTIONABLE = {"", ST_QUEUED, ST_RETRY, ST_APPROVED}
# Human-set states that mean "fresh start" — reset the attempt counter on pick.
RESET_TRIES = {ST_RETRY, ST_APPROVED}
# Terminal / in-flight → skip
SKIP = {ST_WORKING, ST_DONE, ST_FAILED, ST_BLOCKED, ST_SPEC_READY}

# Autonomy levels — the single source of truth, shared by the agent dispatcher
# (orchestrator) and config validation so the set never drifts between them.
#   spec  = write the OpenSpec change, stop          gated = spec -> human approve -> ship
#   code  = implement, stop before push/deploy       ship  = full pipeline (commit/push/deploy)
AUTONOMY_LEVELS = {"spec", "code", "ship", "gated"}
AUTONOMY_CHOICES = "spec|code|ship|gated"  # human-facing message form


@dataclass
class Config:
    # --- Sheet backend ---
    backend: str = field(default_factory=lambda: os.getenv("SHEET_BACKEND", "google"))
    sheet_id: str = field(default_factory=lambda: os.getenv("SHEET_ID", ""))
    sa_json: str = field(default_factory=lambda: os.getenv("GOOGLE_SA_JSON", ""))
    mock_path: str = field(
        default_factory=lambda: os.getenv("MOCK_SHEET_PATH", str(_PROJECT_ROOT / "state" / "mock_sheet.json"))
    )

    # --- Repo resolution ---
    # Roots searched when a tab binds by bare name instead of an absolute path/url.
    repo_search_roots: tuple[str, ...] = field(
        default_factory=lambda: tuple(
            p.strip()
            for p in os.getenv(
                "REPO_SEARCH_ROOTS",
                f"{Path.home()}/projects",
            ).split(":")
            if p.strip()
        )
    )
    clone_root: str = field(
        default_factory=lambda: os.getenv("CLONE_ROOT", f"{Path.home()}/projects")
    )
    # Colon-separated glob patterns matched (fnmatch) against a discovered repo's name
    # (its path relative to the search root) to PRUNE неактуальные repos from the
    # `_repos` add-repo dropdown. Empty = nothing pruned. Lives in discovery (not the
    # sheet) so the prune survives every `_repos` rebuild — editing the rebuilt tab
    # would not. E.g. REPO_IGNORE="legacy/*:*-archived".
    repo_ignore: tuple[str, ...] = field(
        default_factory=lambda: tuple(
            p.strip()
            for p in os.getenv("REPO_IGNORE", "").split(":")
            if p.strip()
        )
    )

    # --- Agent ---
    # The sheet is read by plain Python/API (no LLM). The model is used ONLY when
    # there's a real task — so default to the most capable one.
    model: str = field(default_factory=lambda: os.getenv("CLAUDE_MODEL", "claude-opus-4-8"))
    # Read-only chat is a Q&A conversation, not code delivery — it doesn't need the
    # most expensive tier. Default to Sonnet so discussion doesn't burn the Opus
    # budget; override with CHAT_MODEL. Tasks still use `model` (Opus).
    chat_model: str = field(default_factory=lambda: os.getenv("CHAT_MODEL", "claude-sonnet-4-6"))
    # full pipeline: commit -> push -> deploy. Values: spec | code | ship | gated
    #   gated = two-stage review: write spec -> spec_ready (human sets `approved`)
    #           -> implement + ship. The safe default for prod-deploying repos.
    autonomy: str = field(default_factory=lambda: os.getenv("AUTONOMY", "ship"))
    # --- Friend sheets (sharing repos with partners) ---
    # Every minted friend file is owned by the service account; share it back to the
    # owner so they keep full access. Empty disables the owner-share (the file is still
    # shared with the recipient). The recipient comes per-share from the dialog.
    owner_email: str = field(default_factory=lambda: os.getenv("OWNER_EMAIL", ""))
    # Default autonomy for a freshly minted friend file: partners file a task → agent
    # writes the spec + branch and parks for owner review. The owner can raise a
    # specific file to `ship` by editing its `_friends` autonomy cell.
    friend_default_autonomy: str = field(
        default_factory=lambda: os.getenv("FRIEND_DEFAULT_AUTONOMY", "gated"))
    agent_timeout: int = field(default_factory=lambda: _int("AGENT_TIMEOUT", 3600))  # seconds
    # Read-only chat agents are short Q&A turns — a much tighter timeout than a full
    # implement-and-ship task.
    chat_timeout: int = field(default_factory=lambda: _int("CHAT_TIMEOUT", 300))  # seconds
    # --- Stall watchdog (Layer 2) -------------------------------------------------
    # The wall-clock `agent_timeout` is a coarse backstop. The stall watchdog kills an
    # agent whose output STREAM has gone silent — the real shape of a hang (an
    # unbounded `until` bash, or a child holding the stdout pipe open so `claude`
    # itself blocks). MUST be ≥ bash_max_timeout_ms (in seconds): a legit max-length
    # bash is silent on the stream until it returns, so a smaller stall would kill it.
    agent_stall_timeout: int = field(default_factory=lambda: _int("AGENT_STALL_TIMEOUT", 1200))  # seconds
    # Chat is read-only Read/Grep — sub-second tool calls, so silence is anomalous fast.
    chat_stall_timeout: int = field(default_factory=lambda: _int("CHAT_STALL_TIMEOUT", 90))  # seconds
    # --- Bounded tool calls (Layer 1) ---------------------------------------------
    # Injected into the `claude -p` child env so a single bash can't run unbounded.
    # The 2-min default kills naive loops fast; the 15-min ceiling leaves room for a
    # legitimate cold `docker compose build` deploy (these repos build on the server).
    bash_default_timeout_ms: int = field(default_factory=lambda: _int("BASH_DEFAULT_TIMEOUT_MS", 120000))
    bash_max_timeout_ms: int = field(default_factory=lambda: _int("BASH_MAX_TIMEOUT_MS", 900000))
    permission_mode: str = field(
        default_factory=lambda: os.getenv("PERMISSION_MODE", "dangerous")
    )  # dangerous | acceptEdits
    claude_bin: str = field(default_factory=lambda: os.getenv("CLAUDE_BIN", "claude"))
    openspec_bin: str = field(default_factory=lambda: os.getenv("OPENSPEC_BIN", "openspec"))
    # Deterministic repo-provisioning engine (one engine, two entry points). A
    # test injects a stub via CREATE_REPO_SCRIPT so the create_repo handler never
    # hits the network.
    create_repo_script: str = field(
        default_factory=lambda: os.getenv("CREATE_REPO_SCRIPT", CREATE_REPO_SCRIPT)
    )
    auto_openspec_init: bool = field(default_factory=lambda: _bool("AUTO_OPENSPEC_INIT", False))

    # --- Loop ---
    poll_interval: int = field(default_factory=lambda: _int("POLL_INTERVAL", 30))  # seconds
    max_tasks_per_cycle: int = field(default_factory=lambda: _int("MAX_TASKS_PER_CYCLE", 0))  # 0 = unlimited
    # Run agents for distinct repos in parallel, but never two in the same working
    # dir (git races). 1 = the old strictly-sequential behaviour.
    max_concurrent_agents: int = field(default_factory=lambda: _int("MAX_CONCURRENT_AGENTS", 2))
    # Read-only chat agents run in their OWN small pool so a quick question is never
    # stuck behind a long implement-and-ship task agent (chat latency must stay low).
    max_concurrent_chats: int = field(default_factory=lambda: _int("MAX_CONCURRENT_CHATS", 2))
    # Dead-letter a row after this many dispatches so a poisoned/quota-starved task
    # can't burn the metered Agent SDK pool forever. `retry`/`approved` reset it.
    max_attempts: int = field(default_factory=lambda: _int("MAX_ATTEMPTS", 3))

    # --- State ---
    state_dir: str = field(default_factory=lambda: os.getenv("STATE_DIR", str(_PROJECT_ROOT / "state")))
    # Cap on raw agent-output dumps kept under state/runs/ (forensics, not authority —
    # the durable-state invariant is about the SHEET, not these). Unbounded, they fill
    # the host's disk (108 MB / 173 files seen in the wild). Oldest are pruned past this
    # count; 0 disables pruning (keep everything).
    runs_keep: int = field(default_factory=lambda: _int("RUNS_KEEP", 300))

    def validate(self) -> list[str]:
        problems: list[str] = []
        if self.backend == "google":
            if not self.sheet_id:
                problems.append("SHEET_ID is empty")
            if not self.sa_json:
                problems.append("GOOGLE_SA_JSON path is empty (service-account key required for writes)")
            elif not Path(self.sa_json).expanduser().exists():
                problems.append(f"GOOGLE_SA_JSON file not found: {self.sa_json}")
        if self.autonomy not in AUTONOMY_LEVELS:
            problems.append(f"AUTONOMY must be {AUTONOMY_CHOICES}, got {self.autonomy!r}")
        if self.friend_default_autonomy not in AUTONOMY_LEVELS:
            problems.append(
                f"FRIEND_DEFAULT_AUTONOMY must be {AUTONOMY_CHOICES}, got "
                f"{self.friend_default_autonomy!r}")
        if self.max_concurrent_agents < 1:
            problems.append("MAX_CONCURRENT_AGENTS must be >= 1")
        # MAX_ATTEMPTS=0 silently dead-letters every task on its first dispatch
        # (`base >= max_attempts` is true at base 0); MAX_CONCURRENT_CHATS<=0 is
        # silently clamped to 1. Surface both in `doctor` instead of masking them.
        if self.max_attempts < 1:
            problems.append("MAX_ATTEMPTS must be >= 1")
        if self.max_concurrent_chats < 1:
            problems.append("MAX_CONCURRENT_CHATS must be >= 1")
        if self.poll_interval < 1:
            problems.append("POLL_INTERVAL must be >= 1")
        if self.runs_keep < 0:
            problems.append("RUNS_KEEP must be >= 0 (0 disables pruning)")
        return problems


def load() -> Config:
    return Config()
