#!/usr/bin/env bash
#
# create_beelink_repo.sh — DETERMINISTIC engine that provisions a brand-new
# beelink repo. ONE engine, TWO entry points: the daemon `create_repo` control
# handler and the `create-beelink-repo` harness skill both shell out to THIS
# script. There is no LLM in the critical path — creating a GitHub repo is
# irreversible, so every step is plain, ordered, idempotent bash.
#
# Steps (openspec/specs/create-new-repo), strictly ordered:
#   1. name=beelink-<raw>; validate <raw> ^[a-z0-9]([a-z0-9.-]*[a-z0-9])?$ (internal
#      dots/hyphens ok, e.g. foo.ru); assert dir absent
#      AND GitHub repo absent (GET /repos/Garbuzenko/$name -> 404).
#   2. copy template -> projects root, EXCLUDING .env.example.
#   3. register in deployer (POST /projects {"name":"$name"}) -> env vars.
#   4. write a real .env (gitignored) from the deployer response + PROJECT_NAME=$name.
#   5. docker-compose.yml: container_name=$name, no host ports, mem_limit/cpus,
#      healthcheck.
#   6. docs/strategy/vision.md from --vision (AUTOGENERATED header).
#   7. openspec init + minimal openspec/project.md.
#   8. git init -> commit (.gitignore keeps .env out).
#   9. create GitHub repo (API+PAT), remote add (SSH), push -u origin main.
#  10. emit JSON {"url":...,"path":...} on stdout for the caller.
#
# Usage:
#   create_beelink_repo.sh --name <raw> [--vision <text>] [--template <name>]
#
# Test seams (env overrides — tests inject stubs so NOTHING hits the network):
#   PROJECTS_ROOT     where the repo dir is created (default $HOME/projects/beelink)
#   TEMPLATE_DIR      template source; if set, overrides --template
#                     (default derived from --template: $HOME/projects/init/<template>, template defaults to init_project)
#   GH_TOKEN_FILE     PAT location              (default $HOME/.config/gh-token)
#   DEPLOYER_URL      deployer base url         (default http://deployer:8000)
#   GITHUB_OWNER      repo owner                (default Garbuzenko)
#   CURL_BIN          curl binary               (default curl)   — stubbed in tests
#   GIT_BIN           git binary                (default git)    — stubbed in tests
#   OPENSPEC_BIN      openspec binary           (default openspec)
#
set -euo pipefail

PROJECTS_ROOT="${PROJECTS_ROOT:-$HOME/projects/beelink}"
# An explicit TEMPLATE_DIR env (tests inject a stub) always wins; otherwise the
# source dir is derived from --template after arg parsing (default init_project).
TEMPLATE_DIR_ENV="${TEMPLATE_DIR:-}"
GH_TOKEN_FILE="${GH_TOKEN_FILE:-$HOME/.config/gh-token}"
DEPLOYER_URL="${DEPLOYER_URL:-http://deployer:8000}"
GITHUB_OWNER="${GITHUB_OWNER:-Garbuzenko}"
CURL_BIN="${CURL_BIN:-curl}"
GIT_BIN="${GIT_BIN:-git}"
OPENSPEC_BIN="${OPENSPEC_BIN:-openspec}"

VISION_AUTOGEN_HEADER='<!-- AUTOGENERATED FROM GOOGLE SHEET — edit in the sheet, not here -->'

die() { echo "create_beelink_repo: $*" >&2; exit 1; }

RAW=""
VISION=""
TEMPLATE="init_project"

while [ $# -gt 0 ]; do
  case "$1" in
    --name)     RAW="${2:-}"; shift 2 ;;
    --vision)   VISION="${2:-}"; shift 2 ;;
    --template) TEMPLATE="${2:-}"; shift 2 ;;
    *)          die "unknown argument: $1" ;;
  esac
done

# Wire --template to the actual source that gets copied (Step 2). An explicit
# TEMPLATE_DIR env overrides; the [ -d ] guard in Step 2 catches a bad name.
TEMPLATE_DIR="${TEMPLATE_DIR_ENV:-$HOME/projects/init/$TEMPLATE}"

# --- Step 1: validate the bare name; assert nothing exists yet --------------
# Validate BEFORE creating anything so an invalid name writes nothing.
[ -n "$RAW" ] || die "missing --name"
if ! printf '%s' "$RAW" | grep -Eq '^[a-z0-9]([a-z0-9.-]*[a-z0-9])?$'; then
  die "invalid name '$RAW' (must match ^[a-z0-9]([a-z0-9.-]*[a-z0-9])?\$ — lower-case, internal dots/hyphens allowed e.g. foo.ru)"
fi

NAME="beelink-$RAW"
DEST="$PROJECTS_ROOT/$NAME"

# Refuse to clobber an existing working dir.
[ ! -e "$DEST" ] || die "target dir already exists: $DEST"

# Refuse if the GitHub repo already exists. A 404 means free; anything else
# (200/403/500) is treated as "exists or unknown" → bail, creating nothing.
TOKEN="$(cat "$GH_TOKEN_FILE")" || die "cannot read PAT from $GH_TOKEN_FILE"
http_code="$(
  "$CURL_BIN" -s -o /dev/null -w '%{http_code}' \
    -H "Authorization: Bearer $TOKEN" \
    -H "Accept: application/vnd.github+json" \
    "https://api.github.com/repos/$GITHUB_OWNER/$NAME"
)" || die "github existence check failed"
if [ "$http_code" != "404" ]; then
  die "github repo $GITHUB_OWNER/$NAME already exists or unverifiable (HTTP $http_code)"
fi

# --- Step 2: copy the template, EXCLUDING .env.example ----------------------
# Hard rule: no .env.example ever lands in a repo.
[ -d "$TEMPLATE_DIR" ] || die "template dir not found: $TEMPLATE_DIR"

# Cleanup on failure: $DEST is provably brand-new this run (Step 1 refused to
# clobber it), so removing it on any error makes the script retryable instead of
# leaving an orphan dir that trips the Step-1 guard forever. Resources created
# outside $DEST (the GitHub repo, the deployer registration) cannot be safely
# auto-undone here (PAT scope / DB side effects) — warn instead so the operator
# can clear the orphan that would otherwise trip the Step-1 / Step-3 guards on a
# retry. We trap EXIT (not ERR): every post-creation failure is reported via
# `cmd || die`, and a command on the left of `||` does NOT fire the ERR trap, so
# an ERR trap would never run on the realistic failure paths. SUCCESS short-circuits
# cleanup on the clean path while preserving the exit code.
SUCCESS=0
GH_CREATED=0
DEPLOYER_REGISTERED=0
cleanup() {
  local rc=$?
  [ "$SUCCESS" = "1" ] && return 0
  rm -rf "$DEST"
  if [ "$DEPLOYER_REGISTERED" = "1" ]; then
    echo "create_beelink_repo: WARN manual cleanup may be required:" \
         "delete the deployer project '$NAME' (DB/user + registry)" >&2
  fi
  if [ "$GH_CREATED" = "1" ]; then
    echo "create_beelink_repo: WARN manual cleanup may be required:" \
         "delete github repo $GITHUB_OWNER/$NAME" >&2
  fi
  exit "$rc"
}
trap cleanup EXIT

mkdir -p "$DEST"
# Copy the whole tree, then strip any .env.example the template may carry.
cp -a "$TEMPLATE_DIR/." "$DEST/"
find "$DEST" -name '.env.example' -type f -delete

# --- Step 3: register in the deployer --------------------------------------
deployer_resp="$(
  "$CURL_BIN" -sf -X POST \
    -H 'Content-Type: application/json' \
    -d "{\"name\": \"$NAME\"}" \
    "$DEPLOYER_URL/projects"
)" || die "deployer registration failed for $NAME"
DEPLOYER_REGISTERED=1

# --- Step 4: write a real .env (gitignored) from the deployer response ------
# The deployer returns env vars as a JSON object (or under an "env" key). We
# project every scalar key=value pair into .env, then stamp PROJECT_NAME last
# so it always wins. python3 is used only for robust JSON parsing (no LLM).
ENV_FILE="$DEST/.env"
python3 - "$deployer_resp" >"$ENV_FILE" <<'PY'
import json, sys
raw = sys.argv[1] if len(sys.argv) > 1 else ""
try:
    data = json.loads(raw) if raw.strip() else {}
except Exception:
    data = {}
env = data.get("env") if isinstance(data, dict) and isinstance(data.get("env"), dict) else data
if not isinstance(env, dict):
    env = {}
for k, v in env.items():
    if isinstance(v, (dict, list)):
        continue
    print(f"{k}={v}")
PY
# Stamp PROJECT_NAME last (overrides anything from deployer) — invariant:
# container_name == PROJECT_NAME == beelink-<name>.
printf 'PROJECT_NAME=%s\n' "$NAME" >>"$ENV_FILE"

# --- Step 5: deterministic docker-compose.yml ------------------------------
# container_name == PROJECT_NAME, NO host ports (Caddy routes), a resource limit
# (deploy.resources.limits) AND a healthcheck — all required by root rules. The
# compose lives under deploy/, so env_file points at the repo-root .env (../.env),
# and the egress-proxy block routes blocked APIs through xray-client (the host's
# only path out to Claude/GitHub/OpenAI/Telegram).
mkdir -p "$DEST/deploy"
cat >"$DEST/deploy/docker-compose.yml" <<COMPOSE
services:
  app:
    image: nginx:alpine              # replace with your runtime image
    container_name: $NAME
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - ../.env
    environment:
      # Прокси для заблокированных API (Claude, Gemini, OpenAI, Telegram, GitHub).
      # Убрать блок целиком, если наружу ходить не нужно.
      HTTP_PROXY:  http://xray-client:8080
      HTTPS_PROXY: http://xray-client:8080
      NO_PROXY:    localhost,127.0.0.1,::1,postgres,qdrant,deployer,whisper,xray-client,caddy
      http_proxy:  http://xray-client:8080
      https_proxy: http://xray-client:8080
      no_proxy:    localhost,127.0.0.1,::1,postgres,qdrant,deployer,whisper,xray-client,caddy
    networks:
      - web
    # NO host ports — Caddy routes by container_name on the shared web network.
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:80/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'

networks:
  web:
    external: true
COMPOSE

# --- Step 6: docs/strategy/vision.md (AUTOGENERATED header) -----------------
mkdir -p "$DEST/docs/strategy"
{
  printf '%s\n\n' "$VISION_AUTOGEN_HEADER"
  printf '%s\n' "$VISION"
} >"$DEST/docs/strategy/vision.md"

# --- Step 7: openspec init + minimal project.md ----------------------------
# A minimal init so the daemon's OpenSpec-only gate passes; deep bootstrap is
# left to the first agent.
( cd "$DEST" && "$OPENSPEC_BIN" init . >/dev/null 2>&1 ) || mkdir -p "$DEST/openspec"
mkdir -p "$DEST/openspec"
if [ ! -s "$DEST/openspec/project.md" ]; then
  cat >"$DEST/openspec/project.md" <<PROJECTMD
# Project: $NAME

## Purpose

$VISION

## Conventions

- OpenSpec-only: every change ships as an OpenSpec change (proposal + spec + tasks).
- Deploy: Docker on the beelink server; container_name == PROJECT_NAME == $NAME.
- No host ports; Caddy routes. Resource limits + healthcheck required.
PROJECTMD
fi

# --- Step 8: git init + commit (.gitignore keeps .env out) ------------------
# Ensure .env is ignored even if the template's .gitignore is missing the rule.
if [ ! -f "$DEST/.gitignore" ] || ! grep -qxF '.env' "$DEST/.gitignore"; then
  printf '\n.env\n' >>"$DEST/.gitignore"
fi
( cd "$DEST" \
  && "$GIT_BIN" init -q \
  && "$GIT_BIN" add -A \
  && "$GIT_BIN" -c user.email=supervisor@beelink -c user.name=supervisor \
        commit -q -m "chore: scaffold $NAME from $TEMPLATE template" \
) || die "git init/commit failed"

# --- Step 9: create the GitHub repo (API+PAT) + SSH push -------------------
"$CURL_BIN" -sf -X POST \
  -H "Authorization: Bearer $TOKEN" \
  -H "Accept: application/vnd.github+json" \
  "https://api.github.com/user/repos" \
  -d "{\"name\": \"$NAME\", \"private\": true, \"description\": \"$NAME (beelink)\"}" \
  >/dev/null || die "github repo creation failed for $NAME"
GH_CREATED=1

REMOTE_URL="git@github.com:$GITHUB_OWNER/$NAME.git"
( cd "$DEST" \
  && "$GIT_BIN" remote add origin "$REMOTE_URL" \
  && "$GIT_BIN" branch -M main \
  && "$GIT_BIN" push -u origin main \
) || die "git remote/push failed"

# --- Step 10: emit {url, path} for the caller ------------------------------
# All side effects committed — disarm the cleanup trap so EXIT keeps $DEST.
SUCCESS=1
REPO_URL="https://github.com/$GITHUB_OWNER/$NAME"
printf '{"url": "%s", "path": "%s"}\n' "$REPO_URL" "$DEST"
